config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  if Rails.env.development?
   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :posts,:path => '/tutorial', except:[:delete] do
  	member do
      put "like", to: "posts#vote"
    end
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users

  get 'link/check'
  get  'pages/about'
  get  'pages/privacy'
  get  '/trending' => 'pages#index'
  root 'posts#index'

  get '/contact' => 'contacts#new'
  resources "contacts", only: [:new, :create]
  get '/search' => 'posts#search', as: 'search'
  get "/users_posts" => 'posts#users_posts'
  get '/likes' => "posts#likes"
  match "*path" => redirect("/"),  via:[:get, :post] #redirect user to home if wrong url entered
end

app/models/post.rb
class Post < ActiveRecord::Base
	 acts_as_votable
	 extend FriendlyId
	 is_impressionable
	 has_many :analytics
	 belongs_to :user
   friendly_id :name, use: :slugged
	# validates_presence_of :name
	#after_save ThinkingSphinx::RealTime.callback_for(:post)

	def self.recommend
		post_id = rand(1..Post.count)
		if Post.exists?(post_id)
			recommend = Post.find(post_id)
		else
			recommend = Post.find(1)
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy,:vote]
  before_filter :authenticate_user!, except: [:sign_out_redirect, :index,:show,:search]
  respond_to :html

  def index
    @posts = Post.where(on_hold: '0').paginate(:page => params[:page], :per_page => 10).order(created_at: :desc)
    respond_with(@posts)
  end

  def show
    @user  = @post.votes_for.up.by_type(User).voters
    impressionist(@post,"#{@post.name}")
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    if current_user == @post.user
      @post.destroy
      redirect_to @post, notice: 'Tutorial Have deleted'
    else
      redirect_to @post, notice: "You don't have permission."
    end
  end

  def vote
    current_user.likes @post
    respond_to do |format|
      #format.json {render json:{count: @post.liked_count }}
      format.js { render :vote, locals: {error_message: "Something went wrong",count: @post.votes_for.size}}
    end
  end

  def search
    @result = Post.search(params[:q])
  end

  def users_posts
    @posts = current_user.posts
  end

  def likes
    @posts = current_user.get_voted Post
  end

  private
  def set_post
    begin
      @post = Post.friendly.find(params[:id])
      redirect_to action: action_name, id: @post.friendly_id, status: 301 unless @post.friendly_id == params[:id]
    rescue ActiveRecord::RecordNotFound
      redirect_to :controller => "posts", :action => "index"
      return
    end
  end

  def post_params
    params.require(:post).permit(:name, :link, :tags, :category)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="pdt50"></div>
<div class="row">
  <div class="col s10 offset-m3">
    <%= form_for(@post) do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
        <div class="input-field col m6 s12">
          <%= f.text_field :name, placeholder: "Name Of the Tutorial", required: true, autofocus:true, spellchecker: true %>
          <label>Name</label>
          <!-- <i class="user icon"></i> -->
        </div>
      </div>
      <div class="row">
        <div class="input-field col m6 s12">
          <%= f.url_field :link, placeholder: "http://www.example.com/", required: true %>
          <label>Link</label>
          <!-- <i class="user icon"></i> -->
        </div>
      </div>
      <div class="row">
        <div class="input-field col m6 s12">
            <%= f.text_field :tags,placeholder: "Tag line", spellchecker: true, required:true %>
            <label>Tags</label>
          <!-- <i class="user icon"></i> -->
        </div>
      </div>
      <div class="row">
        <div class="input-field col m6 s12">
          <%= f.text_field :category,placeholder: "Category", spellchecker: true %>
          <label>Category</label>
           <!-- <i class="user icon"></i> -->
        </div>
      </div>
      <div class="row">
        <div class="input-field col m6 s12">
          <div class="right"><%= link_to 'Back', posts_path, class: "btn waves-effect waves-light" %></div>
            <%= f.button "" , class: "btn waves-effect waves-light" do %>
              Save
              <i class="material-icons right">send</i>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  Materialize.updateTextFields();
</script>

app/views/posts/_post.html.erb
<div class="ui four column doubling stackable grid container post">
  <% @posts.each do |post| %>
    <div class="column">
      <div class="ui blue card">
        <div class="content">
          <!-- <i class="right floated star icon"></i> -->
          <div class="right floated meta"><%= post.created_at.strftime("%d-%b-%Y")%></div>
          <span class="ui avatar image"> <%= avatar_index_url post.user, '30' %> </span>
          <div class="description">
            <%= link_to "#{post.name.titleize.truncate(70)}", post, :target => "_blank"%>
          </div>
        </div>
        <div class="extra content">
          <span class="left floated">
            <i class="check icon"></i>
            <%= pluralize(post.impressionist_count,'View') %>
          </span>
          <span class="right floated">
            <%= link_to like_post_path(post), method: :put, class: "vote", remote: true do %>
              <% if (current_user) && (current_user.voted_for? post) %>
                <i class="like icon active"></i>
                  <%= pluralize(post.votes_for.size, 'Like')%>
              <% else %>
                <i class="like icon"></i>
                <%= pluralize(post.votes_for.size, 'Like')%>
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/posts/_search.html.erb
<form action="/search">
	<div class="ui transparent left icon input">
	  <input type="text" placeholder="Search Tutorials" name="q" autocomplete="off">
	  <i class="search icon"></i>
	</div>
</form>

app/views/posts/edit.html.erb
<!-- <h1 class="ui purple ribbon label">Edit Tutorial</h1> -->
<%= render 'form' %>

<!-- <div class="ui hidden divider"></div>
<div class="ui buttons">
  <div><%#= link_to 'Show', @post, class: "ui small button" %></div>
  <div class="or"></div>
  <div> <%#= link_to 'Back',posts_path, class: "ui small button" %></div>
</div> -->

app/views/posts/index.html.erb
<div class="pdt50"></div>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col s12 m6">
      <div class="card-panel">
        <div class="grey-text text-darken-4 mbr20">
          <%= link_to "#{post.name.titleize.truncate(60)}", post, :target => "_blank"%>
        </div>
        <div class="card-action">
          <span class="vlignt"><%= avatar_index_url post.user, '30' %></span>
          <%= time_ago_in_words(post.created_at) + " ago"%>
          <%= link_to like_post_path(post), method: :put, class: "vote", remote: true do %>
            <% if (current_user) && (current_user.voted_for? post) %>
              <i class="material-icons" style="vertical-align:middle;">star</i>
                <span class="vlignt"><%= pluralize(post.votes_for.size, 'Like')%></span>
            <% else %>
              <i class="material-icons" style="vertical-align:middle;">star_border</i>
              <span class="vlignt"><%= pluralize(post.votes_for.size, 'Like')%></span>
            <% end %>
          <% end %>
          <span class="right">
            <i class="material-icons" style="vertical-align:middle;">visibility</i>
            <%= pluralize(post.impressionist_count,'View') %>
          </span>
        </div>
      </div>
    </div>
  <% end %>
  <div class="container offset-m3 pdt50">
    <%= will_paginate @posts, class:"flickr_pagination"%>
  </div>
</div>
      <!-- <div class="col s12 m6">
        <div class="card small">
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%#= "#{post.name.titleize.truncate(70)}"%><i class="material-icons right">more_vert</i></span>
            <p><%#= link_to "#{post.name.titleize.truncate(70)}", post, :target => "_blank"%></p>
            <p><%#= post.tags%></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">Tutorails was sahred - <%#= time_ago_in_words(post.created_at) + " ago"%><i class="material-icons right">close</i></span>
            <p>By - <%#= avatar_index_url post.user, '30' %> </p>
          </div>
        </div>
      </div> -->

    <!-- <div class="column">
      <div class="ui cards">
        <div class="blue card">
          <div class="content">
            <i class="right floated star icon"></i>
            <div class="right floated meta"><%#= time_ago_in_words(post.created_at) + " ago"%></div>
            <span class="ui avatar image"> <%#= avatar_index_url post.user, '30' %> </span>
            <div class="description">
              <%#= link_to "#{post.name.titleize.truncate(70)}", post, :target => "_blank"%>
            </div>
          </div>
          <div class="extra content">
            <span class="left floated">
              <i class="unhide icon"></i>
              <%#= pluralize(post.impressionist_count,'View') %>
            </span>
            <span class="right floated">
              <%#= link_to like_post_path(post), method: :put, class: "vote", remote: true do %>
                <%# if (current_user) && (current_user.voted_for? post) %>
                  <i class="like icon active"></i>
                    <%#= pluralize(post.votes_for.size, 'Like')%>
                <%# else %>
                  <i class="like icon"></i>
                  <%#= pluralize(post.votes_for.size, 'Like')%>
                <%# end %>
              <%# end %>
            </span>
          </div>
        </div>
      </div>
    </div> -->
  <%#end%>
  <!-- <div class="apple_pagination ui container ">
    <%#= will_paginate @posts%>
  </div>
</div> -->

<!-- <div class="" id="posts">
 <%#= render @posts %>
</div>
<div class="will_paginate_pagination">
  <%#= will_paginate @posts%>
</div>
<div class="" id="loading" style="display:none;">
  Getting More . . .
</div> -->


<!-- <div class= "ui animated selection list">
  <h2 class="ui purple ribbon label"><%=Date.today%></h2>
  <% @posts.each do |post| %>
    <div class="item">
      <%= link_to post, class: "right floated compact" do %>
        <i class='forward icon purple' data-title = "<%= "#{pluralize(post.impressionist_count,'View')}" %>" data-content = 'Check out' data-position="top right" ></i>
      <%end%>
      <div class='right floated compact'><%= avatar_index_url post.user, '30' %> </div>
      <%= link_to like_post_path(post), method: :put, class: "vote left floated", remote: true do %>
        <% if (current_user) && (current_user.voted_for? post) %>
          <div class="ui label">
             <i class="thumbs up icon"></i><%=post.votes_for.size%>
          </div>
        <%else%>
          <div class="ui label">
           <i class="thumbs outline up icon"></i><%=post.votes_for.size%>
          </div>
        <%end%>
      <%end%>
      <div class="content">
        <div class= "header"> <%= link_to "#{post.name.truncate(70)}", link_check_path(name: "#{post.name}"), :target => "_blank",'data-title'=> "#{pluralize(post.impressionist_count,'View')}"%> </div>
      </div>
    </div>
  <%end%>
</div> -->
  <!-- <div class = "apple_pagination"> <%= will_paginate @posts%> </div> -->

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript render(@posts) %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');

app/views/posts/likes.html.erb
<div class="pdt50"></div>
<%unless @posts.blank? %>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col s12 m6">
        <div class="card-panel">
          <div class="grey-text text-darken-4 mbr20">
            <%= link_to "#{post.name.titleize.truncate(60)}", post, :target => "_blank"%>
          </div>
          <div class="card-action">
            <span class="vlignt"><%= avatar_index_url post.user, '30' %></span>
            <%= time_ago_in_words(post.created_at) + " ago"%>
            <%= link_to like_post_path(post), method: :put, class: "vote", remote: true do %>
              <% if (current_user) && (current_user.voted_for? post) %>
                <i class="material-icons" style="vertical-align:middle;">star</i>
                  <span class="vlignt"><%= pluralize(post.votes_for.size, 'Like')%></span>
              <% else %>
                <i class="material-icons" style="vertical-align:middle;">star_border</i>
                <span class="vlignt"><%= pluralize(post.votes_for.size, 'Like')%></span>
              <% end %>
            <% end %>
            <span class="right">
              <i class="material-icons" style="vertical-align:middle;">visibility</i>
              <%= pluralize(post.impressionist_count,'View') %>
            </span>
          </div>
        </div>
      </div>
    <%end%>
  </div>
<%else%>
  <div class="container">
    <div class="header">
      You have not liked any tutorails yet, show your love to tutorials which helped you in enriching your knowledge.
    </div>
    <p> <%= link_to "Get Started!", '/tutorial/new' %> </p>
  </div>
<%end%>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/search.html.erb
<div class= "ui animated selection list">
  <h2 class="ui purple ribbon label">Search Result</h2>
  <% unless @result.blank? %>
	  <% @result.each do |post| %>
	    <div class="item">
	      <%= link_to post, class: "right floated compact" do %>
	        <i class='forward icon purple' data-title = "<%= "#{pluralize(post.impressionist_count,'View')}" %>" data-content = 'Check out' data-position="top right" ></i>
	      <%end%>
	      <div class='right floated compact'><%= avatar_index_url post.user, '30' %> </div>
	      <%= link_to like_post_path(post), method: :put, class: "vote left floated", remote: true do %>
	        <% if (current_user) && (current_user.voted_for? post) %>
	          <div class="ui label">
	             <i class="thumbs up icon"></i><%=post.votes_for.size%>
	          </div>
	        <%else%>
	          <div class="ui label">
	           <i class="thumbs outline up icon"></i><%=post.votes_for.size%>
	          </div>
	        <%end%>
	      <%end%>      
	      <div class="content">
	        <div class= "header"> <%= link_to "#{post.name.truncate(70)}", link_check_path(name: "#{post.name}"), :target => "_blank",'data-title'=> "#{pluralize(post.impressionist_count,'View')}"%> </div>
	      </div>
	    </div>
	  <%end%>
	<%else%>
	<br> <br>
		<div class="ui purple message"><p>We are sorry! We couldn't find what you were looking for. Please try modifying your search query or please try again later.</p></div>
	<%end%> 
</div>
<%= link_to 'Back',:back, class: "ui small button" %>

app/views/posts/show.html.erb
<div class="pdt50"></div>
<div class="row">
  <div class="col s10 offset-m2">
    <h3><%= @post.name %></h3>
    <p>
      <strong>Link:</strong>
      <%= link_to "#{@post.link}", link_check_path(name: "#{@post.name}"), :target => "_blank", id: 'link', value: "#{@post.name}" %>
    </p>
    <p>
      <strong>Tag Line:</strong>
      <% if @post.tags.blank? %>
        No Tag line provided
      <%else%>
        <%= @post.tags %>
      <%end%>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @post.category %>
    </p>
    <p>
      <strong>Votes:</strong>
      <% if @user.blank? %>
       <%= link_to like_post_path(@post), method: :put, class: "vote", remote: true do %>
        <div class="ui label">
          <i class="like icon"></i>No Votes. Be the first to like the tutorial.
        </div>
       <%end%>
        <br /> <br />
      <%else%>
        <div>
          <% @user.each do |item| %>
            <span>
              <%= avatar_url item, '48' %>
            </span>
          <%end%>
        </div>
      <%end%>
    </p>
    <div>
      <% if @post.user == current_user %>
        <%= link_to 'Edit', edit_post_path(@post), class: "btn waves-effect waves-light" %>
      <% end %>
        <%= link_to "Back", :back, class: "btn waves-effect waves-light" %>
        <%= link_to "Suprise Tutorial","/tutorial/#{Post.recommend.slug}", class: "btn waves-effect waves-light"%>
    </div>

    <!-- <div class="">
      <%= link_to "" ,@post.link, id: "anchor"%>
      <div class="urlive-container">
        <span class="loading">
          <div class="ui active inverted dimmer">
          <div class="ui text loader">Preparing Files</div>
        </div>
      </span>
        <div class="failed"></div>
      </div>
    </div> -->
  </div>
</div>

<!-- <script type="text/javascript">
$(function(){
  $('#anchor').urlive({
    imageSize: 'small',
    callbacks:{
      onStart: function(){
          $('.loading').show();
      },
      onSuccess: function(){
        $(".loading").hide();
      },
      onLoadEnd: function(){
          $('.loading').hide();
      },
      noData: function () {
          $('.loading').hide();
          $(".failed").append("<div class='ui orange message'>Failed to load Preview.</div>");
      },
      onFail: function() {
        $('.loading').hide()
      }
    }
  });
   $('img').popup({inline: true});
   $('.urlive-container').on('click',function(){
    var value = $('#link').attr('value');
      //var href = $('.urlive-link').attr('href');
      $.ajax({
        type: 'GET',
        url: '/link/check',
        data: {name: value}
      });
   });
});
</script> -->

app/views/posts/users_posts.html.erb
<div class="pdt50"></div>
<% unless @posts.blank? %>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col s12 m6">
        <div class="card-panel">
          <div class="grey-text text-darken-4 mbr20">
            <%= link_to "#{post.name.titleize.truncate(60)}", post, :target => "_blank"%>
          </div>
          <div class="card-action">
            <span class="vlignt"><%= avatar_index_url post.user, '30' %></span>
            <%= time_ago_in_words(post.created_at) + " ago"%>
            <%= link_to like_post_path(post), method: :put, class: "vote", remote: true do %>
              <% if (current_user) && (current_user.voted_for? post) %>
                <i class="material-icons" style="vertical-align:middle;">star</i>
                  <span class="vlignt"><%= pluralize(post.votes_for.size, 'Like')%></span>
              <% else %>
                <i class="material-icons" style="vertical-align:middle;">star_border</i>
                <span class="vlignt"><%= pluralize(post.votes_for.size, 'Like')%></span>
              <% end %>
            <% end %>
            <span class="right">
              <i class="material-icons" style="vertical-align:middle;">visibility</i>
              <%= pluralize(post.impressionist_count,'View') %>
            </span>
          </div>
        </div>
      </div>
    <%end%>
  </div>
<%else%>
  <div class="container">
    <div class="header">
      You have not posted any tutorails yet, share your best tutorials with us.
    </div>
    <p> <%= link_to "Get Started!", '/tutorial/new' %> </p>
 </div>
<%end%>

app/views/posts/vote.js.erb
$('.vote').on('ajax:success', function () { $(this).html("<i class='material-icons' style='vertical-align:middle;'>star</i>"); });